### ISSUE TITLE
Set IAM Auth per user not proxy wide

### ISSUE THREAD

**Issue by johnathan99j** [terraform-aws-modules/terraform-aws-rds-proxy#16]
## Is your request related to a problem? Please describe.
Currently iam_auth is set proxy wide and pulled into the dynamic auth loop in the aws_db_proxy resource. With this approach you can't break down different users into IAM and non IAM authentication for the proxy.

## Describe the solution you'd like.
Make it so that iam_auth can be pulled from the secrets object into the dynamic auth block instead of being set globally for the whole proxy.

**Comment by bryantbiggs** [comment]
Do you have any documentation that references this approach?

**Comment by johnathan99j** [comment]
[Here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy#iam_auth) is the documentation for the aws_db_proxy resource, specifically the `iam_auth` argument for the `auth` block.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.0.0 :tada:
