### ISSUE TITLE
Can't have more than 1 secret

### ISSUE THREAD

**Issue by gaspo53** [terraform-aws-modules/terraform-aws-rds-proxy#19]
Can't have more than 1 secret for the input variable **secrets**. 
It errors out with the following:
`│ Error: Insufficient auth blocks
│
│   on .terraform/modules/rds_proxy/main.tf line 13, in resource "aws_db_proxy" "this":
│   13: resource "aws_db_proxy" "this" {
│
│ At least 1 "auth" blocks are required.
╵
╷
│ Error: Invalid dynamic for_each value
│
│   on .terraform/modules/rds_proxy/main.tf line 26, in resource "aws_db_proxy" "this":
│   26:     for_each = var.secrets
│
│ Cannot use a map of object value in for_each. An iterable collection is required.`

Thanks in advance

**Comment by gaspo53** [comment]
Apparently is something related of the map key. Having this makes it to work:
`
  secrets = {
    root = {
      description = aws_secretsmanager_secret.rds_proxy_root.description
      arn         = aws_secretsmanager_secret.rds_proxy_root.arn
      kms_key_id  = aws_secretsmanager_secret.rds_proxy_root.kms_key_id
    }
    service_preprod = {
      description = aws_secretsmanager_secret.rails_app_preprod.description
      arn         = aws_secretsmanager_secret.rails_app_preprod.arn
      kms_key_id  = aws_secretsmanager_secret.rails_app_preprod.kms_key_id
    }
  }
`

**Comment by bryantbiggs** [comment]
please provide the details requested in the bug/feature request templates

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.0.0 :tada:
